### ISSUE TITLE
Solução Proposta

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T03-CerradoTech#4]
Objetivo: Reativar o aplicativo RADIS Cerrado.
O resto perfumaria, ainda mais quando vem cheio de adjetivos... "robusta, confiável e escalável"
O que deve ser feito: "solucionando os problemas técnicos e de usabilidade que o deixaram fora do ar"
Para quê: "atender à necessidade crítica de monitoramento ambiental e regularização de propriedades rurais no Cerrado".

Ou seja, ajustem, e deixem apenas o objetivo.

**Comment by camilascareli** [comment]
fix(solucao): tirando adjetivos para deixar uma leitura mais clara
