### ISSUE TITLE
Estratégias de ESW

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T03-CerradoTech#6]
**Menor Complexidade de Implementação:**

O Modelo Espiral é um dos processos mais complexos de implementar, devido à necessidade de avaliações constantes de risco e revisões iterativas. Ele exige um planejamento detalhado e uma gestão rigorosa, o que aumenta a complexidade, especialmente em comparação com modelos mais simples, como RAD.

O RUP é, de fato, um processo estruturado e pode se tornar complexo devido ao envolvimento de diversas disciplinas (como Análise, Design, Implementação, Testes) e papéis específicos (Analistas, Arquitetos, Desenvolvedores, Testadores).

O texto mais adequado, seria:
 - Modelo espiral: É complexo de implementar devido ao foco contínuo em análise de risco e avaliações rigorosas em cada iteração. É mais adequado para projetos com alta incerteza e riscos significativos, independentemente do tamanho do projeto.
  - RUP: Apresenta alta complexidade por envolver várias disciplinas e papéis específicos, sendo mais indicado para projetos grandes e de longo prazo que exigem formalização e gestão detalhada.
  
  A partir disso, avaliem se, de fato, irão manter o modelo espiral.

**Comment by patrickacs** [comment]
Alterações feitas no commit fa8bf2a
